# Generated by Django 3.2.7 on 2021-10-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibMangSys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=30, verbose_name='book name')),
                ('authorname', models.CharField(max_length=30, verbose_name='author name')),
                ('bookno', models.CharField(max_length=30, verbose_name='bookno')),
                ('catogory', models.CharField(max_length=10, verbose_name='catogory')),
                ('username', models.IntegerField(verbose_name='quantity')),
            ],
        ),
    ]
