# Generated by Django 3.2.7 on 2021-10-14 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibMangSys', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='username',
            new_name='quantity',
        ),
    ]
