# Generated by Django 3.2.7 on 2021-10-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibMangSys', '0003_rename_username_book_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='catogory',
            new_name='category',
        ),
    ]
