# Generated by Django 3.2.7 on 2021-10-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibMangSys', '0007_auto_20211020_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbook',
            name='fine',
            field=models.IntegerField(default=0),
        ),
    ]
