# Generated by Django 3.2.7 on 2021-10-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibMangSys', '0008_issuedbook_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedbook',
            name='latedays',
            field=models.IntegerField(default=0),
        ),
    ]
